apiVersion: batch/v1
kind: Job
metadata:
  name: app-job
spec:
  completions: 5
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      name: app-job
    spec:
      containers:
        - name: counter
          image: ubuntu
          command:
            - "bin/bash"
            - "-c"
            - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; sleep 1 ; done"
      restartPolicy: Never
