apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: multi-container-pod
spec:
  containers:
  - name: nginx
    image: nginx

  - name: busybox
    image: busybox
    command: 
      - sleep
      - "3600"
