apiVersion: v1
kind: Pod
metadata: 
  name: app-livenessprobe
spec:
  containers:
  - name: app-livenessprobe
    image: tomcat:9.0-jdk8-corretto
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 10
