apiVersion: v1
kind: Pod
metadata:
  name: app-volumemounts
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: app-volumeMounts
    volumeMounts:
    - mountPath: /opt/test
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /usr/local
      type: Directory
