apiVersion: v1
kind: Pod
metadata:
  name: app-resources
spec:
  containers:
  - name: app-resources
    image: busybox
    resources:
      limits:
        cpu: "1"
        memory: "512Mi"
      requests:
        cpu: "0.5"
        memory: "256Mi"
