apiVersion: v1
kind: Pod
metadata:
  name: app-readinessprobe
spec:
  containers:
  - name: app-readinessprobe
    image: tomcat:9.0-jdk8-corretto
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
