apiVersion: v1
kind: Pod
metadata:
  name: app-secret
spec:
  containers:
    - name: app-secret
      image: nginx
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret
